"use client";

import { FormEvent, useState } from "react";
import useSWR from "swr";
import { Plus } from "lucide-react";
import { fetchRaw } from "@/lib/swr";

interface Program { id: string; name: string; slug: string; referredBenefitAmount: number; referrerRewardAmount: number; expiresAfterDays: number; isActive: boolean; }

export default function ReferralProgramsPage() {
  const { data, mutate } = useSWR<{ success: boolean; data: Program[] }>("/admin/referral-programs", fetchRaw);
  const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: "", slug: "", referredBenefitAmount: "", referrerRewardAmount: "", expiresAfterDays: "90" });
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { const response = await fetch("/api/admin/referral-programs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, referredBenefitAmount: Number(form.referredBenefitAmount), referrerRewardAmount: Number(form.referrerRewardAmount), expiresAfterDays: Number(form.expiresAfterDays) }) }); if (!response.ok) throw new Error("Unable to create program"); setOpen(false); setForm({ name: "", slug: "", referredBenefitAmount: "", referrerRewardAmount: "", expiresAfterDays: "90" }); await mutate(); } finally { setSaving(false); } }
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Referral programs</h1><p className="mt-1 text-sm text-slate-500">Configure referral benefits and store-credit rewards.</p></div><button onClick={() => setOpen(!open)} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> New program</button></div>{open && <form onSubmit={submit} className="grid gap-3 rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900 md:grid-cols-2"><input required placeholder="Program name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-lg border p-2 text-sm dark:bg-slate-800" /><input required placeholder="Slug" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} className="rounded-lg border p-2 text-sm dark:bg-slate-800" /><input required type="number" min="0" placeholder="Referred benefit" value={form.referredBenefitAmount} onChange={(e) => setForm({ ...form, referredBenefitAmount: e.target.value })} className="rounded-lg border p-2 text-sm dark:bg-slate-800" /><input required type="number" min="0" placeholder="Referrer reward" value={form.referrerRewardAmount} onChange={(e) => setForm({ ...form, referrerRewardAmount: e.target.value })} className="rounded-lg border p-2 text-sm dark:bg-slate-800" /><input required type="number" min="1" placeholder="Expires after days" value={form.expiresAfterDays} onChange={(e) => setForm({ ...form, expiresAfterDays: e.target.value })} className="rounded-lg border p-2 text-sm dark:bg-slate-800" /><button disabled={saving} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">{saving ? "Creating…" : "Create program"}</button></form>}<div className="overflow-x-auto rounded-xl border bg-white dark:border-slate-800 dark:bg-slate-900"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr><th className="p-4">Program</th><th className="p-4">Referred benefit</th><th className="p-4">Referrer reward</th><th className="p-4">Expiry</th></tr></thead><tbody>{(data?.data ?? []).map((program) => <tr key={program.id} className="border-b last:border-0"><td className="p-4 font-semibold">{program.name}<div className="text-xs font-normal text-slate-500">{program.slug}</div></td><td className="p-4">₹{program.referredBenefitAmount}</td><td className="p-4">₹{program.referrerRewardAmount}</td><td className="p-4">{program.expiresAfterDays} days</td></tr>)}</tbody></table></div></div>;
}